title: みむねこのーと
description: >
  みむねこ用Jekyllです。
baseurl: "/mimnekonote"
url: "https://mimneko.github.io"

author:
  name: mimneko
  github: mimneko

paginate: 3
paginate_path: page:num

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-feed

plugins:
  - jekyll-paginate
