title: みむねこのーと
description: >
  みむねこ用Jekyllです。
baseurl: "/mimnekonote"
url: "https://mimneko.github.io"

author:
  name: みむねこ
  github: mimneko

paginate: 3
paginate_path: page:num

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-toc

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

toc:
  min_level: 2
  max_level: 3
  list_id: toc-content
  ordered_list: true

permalink: /:categories/:title/
future: true

defaults:
  - scope:
      path: ""
    values:
      toc: true
      layout: "post"
      categories: "uncategorized"
