title: みむねこのーと
description: みむねこ用Jekyllです。
baseurl: "/mimnekonote"
url: "https://mimneko.github.io" # サイトのURL。
author:
  name: みむねこ
  github: mimneko

plugins:
  - jekyll-toc

#timezone: Asia/Tokyo

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..3
toc:
  min_level: 2
  max_level: 3
  list_id: toc-content
  ordered_list: true

permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      author: "みむねこ"
      layout: post
      toc: true
