title: みむねこのーと
description: >
  みむねこ用Jekyllです。
baseurl: "/mimnekonote"
url: "https://mimneko.github.io"

author:
  name: みむねこ
  github: mimneko

paginate: 3
paginate_path: page:num

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-feed

plugins:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:title/
future: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      categories: "uncategorized"
