title: みむねこのーと
description: みむねこ用Jekyllです。
baseurl: "/mimnekonote"
url: "https://mimneko.github.io" # サイトのURL。
author:
  name: みむねこ
  github: mimneko

permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      author: "みむねこ"
      layout: post

nav:
  - name: "数学"
    url: "/math/"
    children:
      - name: "代数学"
        url: "/math/algebra/"
  - name: "デザイン"
    url: "/design/"
    children:
      - name: "スライド"
        url: "/design/slide/"
