# .github/workflows/jekyll.yml

name: 更新したファイルをwebページに反映

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # 必要な最新のコミットのみクローン

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # 使用するRubyのバージョン

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
